### ISSUE TITLE
submitForm

### ISSUE THREAD

**Issue by gcw07** [Modelizer/Selenium#10]
There are a couple things with the submitForm method.

```
protected function submitForm($inputs, $selector)
{
        $form = $this->byCssSelector($selector);
        $this->type_information($inputs);
        $form->submit();
        return $this;
}
```

Looks like **type_information** is actually **typeInformation**. Also, the submitForm variables are reversed from the standard laravel one. It is $selector, $inputs instead. Sorry I didn't have time to do a real pull request and fix it myself. Figured I'd at least report it for now.

**Comment by Modelizer** [comment]
Thanks for reporting. :+1: 

@jhoopes I think we need to fix this and add it to our next release change log.

**Comment by jhoopes** [comment]
Hi @gcw07 thanks for reporting this issue.  I had already fixed the typeInformation bug with writing tests for the package.  I have now also switched the parameter order, and when that gets released with tests, it should be up there.

Thanks,
