### ISSUE TITLE
Missing Imports

### ISSUE THREAD

**Issue by gcw07** [Modelizer/Selenium#12]
The **InteractWithPage** trait is missing the imports for both exceptions:

CannotClickElement
CannotFindElement

**Comment by Modelizer** [comment]
Noted 👍 

Will be added in future released.

**Comment by Modelizer** [comment]
`imports for both exceptions` can you elaborate this point?

**Comment by Modelizer** [comment]
Fixed.

Thanks to report.

**Comment by gcw07** [comment]
https://github.com/Modelizer/Selenium/blob/master/src/Services/InteractWithPage.php

Should have:

use Modelizer\Selenium\Exceptions\CannotClickElement;
use Modelizer\Selenium\Exceptions\CannotFindElement;

**Comment by Modelizer** [comment]
Initially, I felt it was an additional feature but after few seconds realize it was a bug.

Thanks to report. 👍
