### ISSUE TITLE
click and press methods

### ISSUE THREAD

**Issue by gcw07** [Modelizer/Selenium#13]
OK, I've been playing around with both of these methods and how it searches through xpath. I think they should be changed from this:

`$this->findElement($text, "//button[contains(text(), '{$text}')]")->click();`

to

`$this->findElement($text, "//button[contains(., '{$text}')]")->click();`

Basically the problem is with the way it is, is that text() only will find information if that is the only thing within the element. So for instance, if you have an icon within a button like:

```
<button class="btn btn-primary">
   <i class="fa fa-trash"></i> Delete
</button>
```

It will not find the text "Delete". It only finds it if it is just

```
<button class="btn btn-primary">
   Delete
</button>
```

Same thing for the click method. Change it from this:

`$this->findElement($textOrId, "//a[contains(text(), '{$textOrId}')]");`

to

`$this->findElement($textOrId, "//a[contains(., '{$textOrId}')]");`

I'm not sure there are any downsides to the change, but I'm not an xpath expert so can't be 100% sure of that. But buttons and links often have other elements within and the current implementation with text() does not seem to work with that.

**Comment by Modelizer** [comment]
Yes, agreed I think you are right and found similar [question](http://stackoverflow.com/questions/3655549/xpath-containstext-some-string-doesnt-work-when-used-with-node-with-more).

Thanks again 👍

**Comment by Modelizer** [comment]
Fixed.
