### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by jhoopes** [Modelizer/Selenium#2]
Hi,

So I actually have been working on my own selenium phpunit driver as well.  jhoopes/laravel-selenium-driver   and was wondering if maybe we'd just work on combining the two?  I've got a lot of the API fleshed out, including support for working with databases, interacting with pages, as well as specifying options with the selenium driver itself.  

Right now, things are working on a mac with safari/chrome/firefox, and haven't tested windows, but I do like the idea with combining the selenium jar file and chrome driver.  

What do you think?

**Comment by Modelizer** [comment]
Hi @jhoopes,
   I really like your idea and even I was thinking to add other browser support, config file, and other stuff. But what I think right now is to make it really simple for the user to get started quickly.

   I suggest you to start dividing your package specific functionality into PRs and will start merging it one by one. Once your package is fully merged with this package then ill add you in the member list. What do you think?

  Feel free to share your thoughts. :)

**Comment by jhoopes** [comment]
Hi,

Thanks for getting back, makes sense to make it simple for the user to get started quickly, @pelletiermaxime has also started doing some things as well.  

The other thing that I've been thinking about though is maybe we should ask Jeffrey what he's planning on doing, or is already working on, as he did say that he'd like what he started with the PHPUnit Selenium 2 driver to eventually be in a package.  He's also working on his testing book as well.  

Do you think maybe we make a fork of his integrated package, make a branch, and turn it into what we're doing, since that's what everyone uses his integrated package for now anyway.  I'd hate to end up duplicating a lot of work just for some differences in specific functionality.

Otherwise, I suppose I can start working on PR's here.  Although I do think maybe we should change the name of this repository if that's where we're keeping everything, as just titling it "selenium" isn't really descriptive of what this package does and is, as it could be confused for the actual selenium webdriver.

**Comment by Modelizer** [comment]
@jhoopes taking integrated package fork will be too overwhelming because this package is specifically for selenium.

Also, lots of API of Integrated package is been pulled into Laravel core, so it might be possible in future @JeffreyWay will abandon that package. 

If @JefferyWay can help us to set the roadmap for this package then it will be very useful.

**Comment by jhoopes** [comment]
Yeah, either way, but looking through the issues on the integrated package, most people are asking for selenium only things anyway.

Also, instead me forking and making PR's from my fork, and then adding me as a collaborator, would you mind making me a collaborator and I just make feature branches to then make PR's to the master branch?

Thanks,

**Comment by Modelizer** [comment]
@jhoopes made you a collaborator. But please make sure before merging any PR I review it first.

Thanks.
