### ISSUE TITLE
General error: 1 no such table: users

### ISSUE THREAD

**Issue by tyler36** [Modelizer/Selenium#22]
Firstly, thanks for taking the time to create and support the package. 

The example test (via "artisan selenium:make:test SeleniumExampleText") works fine for me during installation.

I'm trying to add addition data to the database during the test.
```
        factory(App\User::class)->create();        
        $this->visit('/');
```

The factory command functions if I use tinker, so I know it's setup. If I switch the extends to 'TestCase' and use the 'DatabaseMigrations' trait, everything passes. 

I guess it's a database configuration issue? How do I configure the database settings for Selenium?
Thanks in advance ....

OS: Win10
Laravel: 5.3.22

**Comment by Modelizer** [comment]
Thanks! 
Try setting DB config in `phpunit.xml` file as an environment variable. You can use this file as a reference https://github.com/Modelizer/Selenium/blob/master/phpunit.xml.dist

**Comment by tyler36** [comment]
OK ... got it working. It didn't like my existing phpunit.xml configuration with the lines:
```
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
```

Using a real database connection functions, but any changes are maintain.
Does this package support the DatabaseTransactions through the default trait? 
I tried added the following line and 
```
use Illuminate\Foundation\Testing\DatabaseTransactions;

class SeleniumExampleTest extends SeleniumTestCase
{
    use DatabaseTransactions;
....
```

but the database maintains the changes.

**Comment by Modelizer** [comment]
ping @jhoopes...

**Comment by Modelizer** [comment]
Right now we haven't added explicit support for it but you may give a try.

Also, you can submit a PR to update readme for adding environment variables for database connection while testing with this package.

Thanks.
