### ISSUE TITLE
Usage on non local environment

### ISSUE THREAD

**Issue by edibez** [Modelizer/Selenium#28]
Hi 

First of all what a great library ! Thank you for this. I have built several site with Laravel but I am quite new with Selenium automated testing, and trying to incorporate Selenium on my current project. I have a few questions that would be great if you can enlighten 

1. Me and my team don`t develop locally nor use container. We develop on our dev server under CentOS . Will it be possible to run the test scripts in a non local environment ? 
2. When i run the php artisan selenium:start it give me this message :

![screen shot 2016-12-28 at 10 54 23 am](https://cloud.githubusercontent.com/assets/1262608/21513489/d0b3d140-cceb-11e6-88aa-0fb6b40f1ca0.png)

Is this mean the Selenium Server running correctly ? And should I run the selenium server each time before i run phpunit ? 

Thank you .

**Comment by Modelizer** [comment]
Thanks @edibez 

Yes, you need to run selenium server whenever you want to test cases or you may keep it running whenever you boot your centos. This may help you to configure a headless testing https://gist.github.com/textarcana/5855427

Alternate solution will be to use saucelabs.com
