### ISSUE TITLE
$this->be does not work.

### ISSUE THREAD

**Issue by chantezan** [Modelizer/Selenium#30]
I used that code because WithoutMiddleware not work,

```
$middleware = [];
if ( !App::runningUnitTests() ) {
    $middleware = ['auth','roles'];
}
```

but when i run test with selenium  App::runningUnitTests() is true,
so i tried use $this->be(User::find(9)) for skip the loging and throw error :(
`ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\SessionGuard' does not have a method 'driver'`
$this->be(User::find(9)) not have problem with TestCase

**Comment by chantezan** [comment]
duplicated

**Comment by Modelizer** [comment]
https://github.com/Modelizer/Selenium/issues/21
