### ISSUE TITLE
PHPUnit_Extensions_Selenium2TestCase_WebDriverException

### ISSUE THREAD

**Issue by jofecolella** [Modelizer/Selenium#46]
I am having this exception using this package in Laravel 5.4 and Php 7.0 on Ubuntu 14.04 server

I get this error:

1) SeleniumExampleTest::testExample
PHPUnit_Extensions_Selenium2TestCase_WebDriverException: 

/home/vagrant/Code/nocnoc/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:165
/home/vagrant/Code/nocnoc/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:71
/home/vagrant/Code/nocnoc/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/SessionStrategy/Isolated.php:67
/home/vagrant/Code/nocnoc/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:296
/home/vagrant/Code/nocnoc/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:337
/home/vagrant/Code/nocnoc/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:314

I don't know how to solve it.

**Comment by Modelizer** [comment]
Try stable version. If it still not fix then please give us a brief message what do you see in console?
