### ISSUE TITLE
Use in console command ?

### ISSUE THREAD

**Issue by ftrudeau** [Modelizer/Selenium#49]
Hello ! 

Thanks for this package. I'd like to use it in the scope of an artisan console command, and not in a test class.  Is this at all possible, and how could this be achieved ?

Thanks.

**Comment by Modelizer** [comment]
You need to import all the things from this class https://github.com/Modelizer/Laravel-Selenium/blob/master/src/SeleniumTestCase.php

but why you want to do it?

**Comment by ftrudeau** [comment]
Because I want to use Selenium to automate some tasks unrelated to testing.
I figured it out.
Thanks for the reply ; )
