### ISSUE TITLE
Can't find element

### ISSUE THREAD

**Issue by ttimot24** [Modelizer/Selenium#50]
Hi!

My tests can't find none of the elements.

Eg:
`$this->visit('/')->wait(5)->findElement('email');`

The email element is surelly there. The id and the name attribute is 'email'.

What could be the problem?

**Comment by Modelizer** [comment]
Can you please provide me with the Laravel version? and did you did any alteration? or you got any error in console while running selenium server etc?

**Comment by ttimot24** [comment]
Hi!

Okey a found out it works with chrome but not with firefox. It's strange. I use an external selenium server, with external geckodriver. All of them are the latest release.

**Comment by Modelizer** [comment]
Not sure. Try lower version of firefox or upgrade to 2.0 of this package.
