### ISSUE TITLE
ReflectionException - After upgrade to Laravel 5.6

### ISSUE THREAD

**Issue by LarryEitel** [Modelizer/Selenium#51]
$ `php artisan selenium:start`

Returns:
```
   ReflectionException  : Class Symfony\Component\Process\ProcessBuilder does not exist

  at C:\_dk\sel56\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:155
    151|         if (array_key_exists($parameter->name, $parameters)) {
    152|             $dependencies[] = $parameters[$parameter->name];
    153|
    154|             unset($parameters[$parameter->name]);
  > 155|         } elseif ($parameter->getClass()) {
    156|             $dependencies[] = $container->make($parameter->getClass()->name);
    157|         } elseif ($parameter->isDefaultValueAvailable()) {
    158|             $dependencies[] = $parameter->getDefaultValue();
    159|         }

  Exception trace:

  1   ReflectionParameter::getClass()
      C:\_dk\sel56\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:155

  2   Illuminate\Container\BoundMethod::addDependencyForCallParameter(Object(Illuminate\Foundation\Application), Object(
ReflectionParameter), [], [])
      C:\_dk\sel56\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:116

  Please use the argument -v to see more details.
```

**Comment by Modelizer** [comment]
I found a fix by replacing line https://github.com/Modelizer/Laravel-Selenium/blob/v1.2.2/src/Console/BootSelenium.php#L34&L48

to
```php
$cmd = implode([
    'java',
    '-jar',
    static::prependPackagePath('selenium.jar'),
    $this->getWebDriver(env('DEFAULT_BROWSER', 'chrome')),
], ' ');

echo shell_exec($cmd.' '.$this->getSeleniumOptions());
```

but problem is more severe. https://github.com/giorgiosironi/phpunit-selenium/ needs to have compatibility with phpunit/phpunit. It is in my todo list to make some core API changes. https://github.com/Modelizer/Laravel-Selenium/projects/3 but if you can submit PR would be appriciated.  Thanks.

For now I need to remove support for Laravel 5.6 :/

**Comment by LarryEitel** [comment]
I made your hack to a vanilla Laravel 5.6 and the error remains. :( I jumped through a bunch of hoops to upgrade to 5.6. This is the only hold up to proceeding. I would be happy to submit a PR if I knew how/where to correct the issue. 

Any work arounds that would enable me to not have to revert back to 5.5 would be AWESOME. :)

**Comment by Modelizer** [comment]
Right now I'm working on a new 2.x release which will have integration of https://github.com/lmc-eu/steward replacing phpunit's selenium.

This upgrade will have 5.6 support but trade off would be only phpunit 5.7 and lower would be acceptable by composer.

Hope I finish it as soon as possible because changing the core API is a big change.

**Comment by LarryEitel** [comment]
Thank you for your prompt response. I can appreciate the challenge to refactor core API.

If your next version breaks previous requirements, perhaps just increment version number and note the revised requirements. :)

I will shelf my 5.6 version and revert back to 5.5 for now.

Thank you for providing this package. :)

**Comment by Modelizer** [comment]
I have not updated readme. but I release 2.0 version of this package https://github.com/Modelizer/Laravel-Selenium/releases/tag/v2.0

Please feel free to submit PR in regards to update readme or any changes. Thanks.
