### ISSUE TITLE
  Error loading class "SeleniumExampleTest" from file "/var/www/html/api/tests/SeleniumExampleTest.php".

### ISSUE THREAD

**Issue by alibaraneser** [Modelizer/Selenium#54]
Hey,

I'm getting this error altough everything done.

error

`  Error loading class "SeleniumExampleTest" from file "/var/www/html/api/tests/SeleniumExampleTest.php". Make sure the class name and namespace matches the file path. `

**Comment by ashikdnd** [comment]
You should use the namespace in the file

```
<?php
namespace Tests;
use Modelizer\Selenium\SeleniumTestCase as SeleniumTestCase;
```
