### ISSUE TITLE
use of press on a form submit button fails

### ISSUE THREAD

**Issue by ashikdnd** [Modelizer/Selenium#55]
I'm trying to submit a form but the test fails

```
$this->visit('/')
       ->fill('john', 'username')
       ->fill('doe', 'password')
       ->press('Login');
```
where `Login` is the value of Submit button

**Comment by ashikdnd** [comment]
@Modelizer kindly solve this for me

**Comment by Modelizer** [comment]
Are you using `Login` as text inside the button? If it is anchor tag then please use `click` method.
